services:
  app:
    image: ghcr.io/yohaybn/israeli-financial-overview-app:master
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Map local data directory to container /data directory
      # This will persist settings, results, and logs
      - ./data:/data
    environment:
      - PORT=3000
      - DATA_DIR=/data
