import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult
} from '@playwright/test/reporter';
import fs from 'fs';
import path from 'path';

interface TestSummaryItem {
  suite: string;
  title: string;
  status: 'passed' | 'failed' | 'timedOut' | 'skipped' | 'interrupted';
  durationMs: number;
  error?: string;
}

export default class SummaryReporter implements Reporter {
  private results: TestSummaryItem[] = [];
  private startTime: number = Date.now();

  onBegin(_config: FullConfig, _suite: Suite) {
    this.results = [];
    this.startTime = Date.now();
  }

  onTestEnd(test: TestCase, result: TestResult) {
    const suiteName = test.parent?.title || path.basename(test.location.file, '.spec.ts');
    this.results.push({
      suite: suiteName,
      title: test.title,
      status: result.status,
      durationMs: result.duration,
      error: result.error?.message,
    });
  }

  async onEnd(result: FullResult) {
    const totalDuration = ((Date.now() - this.startTime) / 1000).toFixed(2);
    const passed = this.results.filter(r => r.status === 'passed').length;
    const failed = this.results.filter(r => r.status === 'failed' || r.status === 'timedOut').length;
    const skipped = this.results.filter(r => r.status === 'skipped').length;
    const total = this.results.length;

    const markdownReport = this.generateMarkdownReport({
      total,
      passed,
      failed,
      skipped,
      totalDuration,
      status: result.status,
    });

    const reportPath = path.resolve(process.cwd(), 'test-report.md');
    fs.writeFileSync(reportPath, markdownReport, 'utf8');

    // Also write a copy to playwright-report folder if it exists
    const reportDir = path.resolve(process.cwd(), 'playwright-report');
    if (!fs.existsSync(reportDir)) {
      fs.mkdirSync(reportDir, { recursive: true });
    }
    fs.writeFileSync(path.join(reportDir, 'summary.md'), markdownReport, 'utf8');

    console.log('\n' + '='.repeat(60));
    console.log(`📊 TEST RUN SUMMARY: ${passed}/${total} PASSED (${failed} failed, ${skipped} skipped) in ${totalDuration}s`);
    console.log(`📄 Detailed Report saved to: test-report.md & playwright-report/index.html`);
    console.log('='.repeat(60) + '\n');
  }

  private generateMarkdownReport(summary: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
    totalDuration: string;
    status: FullResult['status'];
  }): string {
    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
    const overallEmoji = summary.failed === 0 && summary.passed > 0 ? '✅' : '❌';

    let md = `# ${overallEmoji} Test Execution Report\n\n`;
    md += `**Date:** ${timestamp}  \n`;
    md += `**Total Duration:** ${summary.totalDuration}s  \n`;
    md += `**Overall Status:** ${summary.status.toUpperCase()}  \n\n`;

    md += `## 📈 Summary Overview\n\n`;
    md += `| Metric | Count | Percentage |\n`;
    md += `| :--- | :--- | :--- |\n`;
    md += `| **Total Tests** | ${summary.total} | 100% |\n`;
    md += `| **Passed** | ${summary.passed} | ${summary.total ? Math.round((summary.passed / summary.total) * 100) : 0}% |\n`;
    md += `| **Failed** | ${summary.failed} | ${summary.total ? Math.round((summary.failed / summary.total) * 100) : 0}% |\n`;
    md += `| **Skipped** | ${summary.skipped} | ${summary.total ? Math.round((summary.skipped / summary.total) * 100) : 0}% |\n\n`;

    md += `## 📋 Detailed Test Results\n\n`;
    md += `| Test Suite | Test Case | Status | Duration | Notes |\n`;
    md += `| :--- | :--- | :---: | :---: | :--- |\n`;

    for (const r of this.results) {
      const statusBadge =
        r.status === 'passed'
          ? '✅ PASS'
          : r.status === 'skipped'
          ? '⏭️ SKIP'
          : '❌ FAIL';
      const durationSec = (r.durationMs / 1000).toFixed(2) + 's';
      const note = r.error ? `\`${r.error.split('\n')[0].replace(/`/g, "'")}\`` : '-';

      md += `| **${r.suite}** | ${r.title} | ${statusBadge} | ${durationSec} | ${note} |\n`;
    }

    if (summary.failed > 0) {
      md += `\n## ⚠️ Failed Tests Diagnostics\n\n`;
      for (const r of this.results.filter(x => x.status === 'failed' || x.status === 'timedOut')) {
        md += `### ❌ ${r.suite} › ${r.title}\n\n`;
        md += `\`\`\`text\n${r.error || 'Test failed without explicit error message'}\n\`\`\`\n\n`;
      }
    }

    md += `\n---\n*Report automatically generated by Playwright Custom Summary Reporter.*\n`;
    return md;
  }
}
